# 2.a. List a share's name and its code
SELECT SHRFIRM, SHRCODE FROM SHARE;

#2.B. LIST DETAILS OF ALL SHARES WITH PRICE LESS THAN $1
SELECT * FROM SHARE
WHERE SHRPRICE<1;

#2.C. LIST THE NAMES AND PRICES OF ALL SHARES WITH A PRICE OF ATLEAST 10
SELECT SHRFIRM, SHRPRICE FROM SHARE
WHERE SHRPRICE>=10;

#2.D. CREATE REPORT SHOWING FIRMNAME, SHAREPRICE, SHAREHOLDING, TOTAL VALUE OF SAHRES HELD.
#(VALUES OF SHARES HELD IS PRICE*QUANTITY)

SELECT SHRFIRM, SHRPRICE, SHRQTY, (SHRPRICE*SHRQTY) AS SHRVALUE FROM SHARE;

#2.E. LIST THE NAMES OF ALL SHARES WITH YIELD EXCEEDING 5%
SELECT SHRFIRM, (SHRDIV/SHRPRICE)*100 AS YIELD FROM SHARE
WHERE ((SHRDIV/SHRPRICE)*100)>5;

#2.F. REPORT TOTAL DIVIDEND PAYMENT OF PATAGONIAN TEA. TOTAL DIVIDEND PAYMENT IS DIVIDEND*QTY
SELECT SHRFIRM, SHRDIV*SHRQTY AS TOTAL_DIV_PAYMENT FROM SHARE
WHERE SHRFIRM= 'Patagonian Tea';

#2.g. FIND ALL SHARES WHERE THE PRICE IS LESS THAN 20 TIMES THE DIVIDEND
SELECT SHRFIRM, SHRPRICE, 20*SHRDIV FROM SHARE
WHERE (SHRPRICE < (20*SHRDIV));

#2.H. FIND THE SHARE WITH THE MINIMUM YIELD
SELECT SHRFIRM, (SHRDIV/SHRPRICE)*100 AS YIELD FROM SHARE
WHERE (SHRDIV/SHRPRICE )*100= (SELECT MIN((SHRDIV/SHRPRICE)*100) FROM SHARE);

#2.I. FIND THE TOTAL VALUE OF ALL SHARES WITH A PE RATIO >10
SELECT SUM(SHRPRICE) FROM SHARE 
WHERE SHRPE>10;

#2.J. FIND THE SHARES WITH MAXIMUM TOTAL DIVIDEND PAYMENT
SELECT SHRFIRM, (SHRDIV*SHRQTY) AS TOTAL_DIV_PAYMENT FROM SHARE
WHERE (SHRDIV*SHRQTY)= (SELECT MAX(SHRDIV*SHRQTY)FROM SHARE);

# 2. k. Find the value of holdings in Abyssinian Ruby and Sri Lankan Gold
#(VALUES OF SHARES HELD IS PRICE*QUANTITY)
SELECT SHRFIRM, SHRPRICE*SHRQTY AS VALUE FROM SHARE
WHERE SHRFIRM REGEXP '^Aby|^Sri';

#2.l. Find the yield of all firms except Bolivian Sheep and Canadian Sugar
SELECT SHRFIRM, (SHRDIV/SHRPRICE)*100 AS YIELD FROM SHARE
WHERE SHRFIRM NOT REGEXP '^Bol|^Can';

#2.m. Find the total value of portfolio
SELECT SHRPRICE*SHRQTY AS VALUE FROM SHARE;

#2.n. List firm name and value in descending order
SELECT SHRFIRM,SHRPRICE*SHRQTY AS VALUE FROM SHARE
ORDER BY SHRFIRM DESC, SHRPRICE*SHRQTY DESC;

#2.O. LIST SHRFIRM WITH NAME CONTAINING 'GOLD'
SELECT SHRFIRM FROM SHARE
WHERE SHRFIRM REGEXP'Gold';

#2.P. FIND SHARES WITH A CODE STARTING WITH 'B'
SELECT SHRFIRM FROM SHARE
WHERE SHRFIRM REGEXP'^B';


