USE Text;

# joining stock table and nation table- natcode-FK_stock and PK_nation
SELECT * FROM stock JOIN nation
ON stock.natcode=nation.natcode;

# WHEN USING GROUP BY THE SELECTED COLUMNS WHICH HAVE UNIQUE VALUES MUST BE AGGREGATED 
# WITH FUNCTIONS LIKE (COUNT, SUM, AVERAGE, MIN, MAX)
# getting stock value in pounds- which is stkqty*stprice*exchangerate
SELECT natname, stkfirm, stkprice, stkqty, exchrate, 
stkprice*stkqty*exchrate AS stkvalue
FROM stock JOIN nation
ON stock.natcode=nation.natcode;

# REPORT THE NUMBER OF STOCKS AND THEIR TOTAL VALUE BY NATION
SELECT SUM(STKQTY),COUNT(*), NATNAME FROM STOCK JOIN NATION
ON STOCK.NATCODE= NATION.NATCODE
GROUP BY NATNAME;

# LIST STOCKS BY NATION, FOR EACH NATION SHOW NUMBER OF STOCKS FOR EACH PE RATIO
# AND THE TOTAL VALUE OF THE STOCK HOLDING IN GBP
SELECT  NATNAME, STKPE, COUNT(*) FROM stock JOIN nation #COUNT(*) WILL COUNT THE NUM OF ROWS WITH THE SAME PAIR OF VALUE (eg: natname UK with stkpe 10 and 16: 2 rows have same values)
ON stock.natcode=nation.natcode
GROUP BY NATNAME, STKPE;

#REPORT THE TOTAL VALUE OF STOCKS FOR NATIONS WITH TWO OR MORE LISTED STOCKS

SELECT NATNAME, SUM(STKPRICE*STKQTY) AS STKVALUE, COUNT(*)
FROM STOCK JOIN NATION
ON STOCK.NATCODE =NATION.NATCODE
GROUP BY NATNAME
HAVING COUNT(*)>=2;
;




